// Bridge DNS — resolve `<name>.well` to a well's DHCP-assigned IP so
// cells can find each other by name without a registry round-trip.
//
// Welld already binds a metadata server on the vmnet bridge IP for
// cooperation signals (host.well at :7879). This adds a sibling UDP
// listener at :5353 that speaks DNS for the `.well` zone.
//
// Why :5353 instead of :53? Privileged ports require root on macOS even
// for non-loopback bind. Cells configure systemd-resolved to query
// `192.168.64.1:5353` for `.well` queries; everything else falls back
// to the DHCP-provided upstream resolver. The cidata's
// /etc/systemd/resolved.conf.d/well.conf drop sets this up.

import { listWells } from "./registry.ts";
import { resolveWellIp } from "./dhcp.ts";
import { log } from "./log.ts";

export const DNS_TTL_SECONDS = 60;
const DNS_ZONE_SUFFIX = ".well";

export interface DnsQuery {
  id: number;
  qname: string;
  qtype: number;
  qclass: number;
  questionEnd: number;
  raw: Uint8Array;
}

// Parse just enough of a DNS query to answer A queries for the .well
// zone. Returns null on malformed input or anything we don't handle
// (multi-question, label compression in the question, EDNS OPT in
// flight — we're fine ignoring those for our use case).
export function parseDnsQuery(buf: Uint8Array): DnsQuery | null {
  if (buf.length < 12) return null;
  const view = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
  const id = view.getUint16(0);
  const qdcount = view.getUint16(4);
  if (qdcount !== 1) return null;

  let pos = 12;
  const labels: string[] = [];
  while (pos < buf.length) {
    const len = buf[pos]!;
    if (len === 0) {
      pos++;
      break;
    }
    // Compression pointers in the question name aren't generated by
    // real resolvers; reject them rather than try to follow.
    if ((len & 0xc0) !== 0) return null;
    pos++;
    if (pos + len > buf.length) return null;
    labels.push(new TextDecoder().decode(buf.slice(pos, pos + len)));
    pos += len;
  }
  if (pos + 4 > buf.length) return null;
  const qtype = view.getUint16(pos);
  const qclass = view.getUint16(pos + 2);
  return {
    id,
    qname: labels.join("."),
    qtype,
    qclass,
    questionEnd: pos + 4,
    raw: buf,
  };
}

// Build a DNS A response. ip=null → NXDOMAIN. Otherwise NOERROR with
// one A record. We compress the answer name as a pointer to the
// question name (offset 12) — saves bytes and matches what every
// real resolver emits.
export function buildDnsResponse(
  query: DnsQuery,
  ip: string | null,
): Uint8Array {
  if (ip === null) {
    const out = new Uint8Array(query.questionEnd);
    out.set(query.raw.slice(0, query.questionEnd));
    const view = new DataView(out.buffer);
    view.setUint16(2, 0x8183);
    view.setUint16(4, 1);
    view.setUint16(6, 0);
    view.setUint16(8, 0);
    view.setUint16(10, 0);
    return out;
  }

  const answerLen = 2 + 2 + 2 + 4 + 2 + 4;
  const out = new Uint8Array(query.questionEnd + answerLen);
  out.set(query.raw.slice(0, query.questionEnd));
  const view = new DataView(out.buffer);
  view.setUint16(2, 0x8180);
  view.setUint16(4, 1);
  view.setUint16(6, 1);
  view.setUint16(8, 0);
  view.setUint16(10, 0);

  let p = query.questionEnd;
  view.setUint16(p, 0xc00c);
  p += 2;
  view.setUint16(p, 1);
  p += 2;
  view.setUint16(p, 1);
  p += 2;
  view.setUint32(p, DNS_TTL_SECONDS);
  p += 4;
  view.setUint16(p, 4);
  p += 2;
  const octets = ip.split(".");
  for (let i = 0; i < 4; i++) {
    out[p + i] = parseInt(octets[i] ?? "0", 10);
  }
  return out;
}

// Strip the .well suffix and return the well name, lowercased.
// Returns null for queries outside our zone.
export function extractWellName(qname: string): string | null {
  const lower = qname.toLowerCase();
  if (!lower.endsWith(DNS_ZONE_SUFFIX)) return null;
  const name = lower.slice(0, -DNS_ZONE_SUFFIX.length);
  if (!name) return null;
  return name;
}

// Resolve `<name>.well` to an IP. Returns null if the well isn't
// registered or has no IP (stopped well that wasn't pinned, just-created
// and not booted yet). Injectable lookups for unit-testability.
//
// Uses resolveWellIp under the hood — that helper returns pinned_ip
// when set, falling back to the DHCP lease lookup for older wells.
export async function resolveWellName(
  qname: string,
  opts?: {
    listWells?: typeof listWells;
    resolveWellIp?: typeof resolveWellIp;
  },
): Promise<string | null> {
  const name = extractWellName(qname);
  if (!name) return null;
  const list = opts?.listWells ?? listWells;
  const ipFor = opts?.resolveWellIp ?? resolveWellIp;
  const records = await list();
  if (!records.some((r) => r.name === name)) return null;
  return await ipFor(name);
}

export interface DnsServerHandle {
  hostname: string;
  port: number;
  close(): void;
}

// Start the bridge DNS listener. Returns a handle with close().
// Skips itself silently if the bind fails (already running, port
// taken, no privilege) — DNS is a comfort feature, not load-bearing
// for the cells team's birth flow.
export async function startBridgeDns(opts: {
  hostname: string;
  port: number;
}): Promise<DnsServerHandle | null> {
  try {
    const socket = await Bun.udpSocket({
      port: opts.port,
      hostname: opts.hostname,
      socket: {
        data: (sock, data, port, address) => {
          handleDnsPacket(data as Uint8Array).then((response) => {
            if (response) sock.send(response, port, address);
          }).catch((e) => {
            log.error("dns query handling failed", {
              err: (e as Error).message,
            });
          });
        },
      },
    });
    log.info("bridge DNS server up", {
      url: `udp://${opts.hostname}:${opts.port}`,
    });
    return {
      hostname: opts.hostname,
      port: opts.port,
      close: () => socket.close(),
    };
  } catch (e) {
    log.error("bridge DNS server failed to start", {
      err: (e as Error).message,
      hostname: opts.hostname,
      port: opts.port,
    });
    return null;
  }
}

async function handleDnsPacket(data: Uint8Array): Promise<Uint8Array | null> {
  const query = parseDnsQuery(data);
  if (!query) return null;
  let ip: string | null = null;
  // Only A/IN. AAAA, MX, TXT, etc. all NXDOMAIN under .well.
  if (query.qtype === 1 && query.qclass === 1) {
    ip = await resolveWellName(query.qname);
  }
  return buildDnsResponse(query, ip);
}
