// Identity rinse — clear hostname, machine-id, ssh host keys, and
// cloud-init semaphores from a running well so the next clone of its
// disk boots clean. Used by `well image save --clean` (or POST
// /v1/wells/images with `clean: true`) to produce directly-forkable
// images without the cells team having to script the rinse themselves.
//
// Why not just clonefile the disk and rely on cloud-init? Because the
// source's identity (hostname, machine-id, ssh host keys) is on the
// disk. A clone DHCPs as the source's hostname until cloud-init
// rewrites it, and welld's lease lookup is by hostname — so welld
// never finds the new well. See docs/cells-integration.md "Identity-
// rinse contract" for the full story.

import { spawn } from "bun";
import { PATHS } from "./state.ts";

// One concatenated shell pipeline. Runs as the well user via sudo.
// Each line is idempotent and best-effort — `cloud-init clean` may
// not exist on every distro, and the manual rm calls below cover
// what it would have done.
//
// Why every line: a fork-from-image boots with the source's MAC
// regenerated by lume (so the disk's pinned-MAC netplan won't match),
// the source's machine-id (which systemd-networkd derives DUID from →
// stale DHCP client identity), the source's ssh host keys (lets the
// fork pretend to be the source), and the source's cloud-init state
// (which gates whether runcmd re-fires on the new instance-id). All
// four classes of state must go.
export const RINSE_SCRIPT = [
  "set -e",
  // Cloud-init's official reset. Clears /var/lib/cloud/instances,
  // /var/lib/cloud/data/instance-id, /var/lib/cloud/sem, and (with
  // --logs) /var/log/cloud-init*. --seed removes a cached datasource
  // hint. `|| true` because cloud-init may be missing on minimal
  // images; we cover the same files manually below.
  "sudo cloud-init clean --logs --seed >/dev/null 2>&1 || true",
  "sudo rm -rf /var/lib/cloud/instances/* /var/lib/cloud/data/* /var/lib/cloud/sem/*",
  // Identity files cloud-init clean doesn't touch.
  "sudo rm -f /etc/machine-id /var/lib/dbus/machine-id",
  "sudo rm -f /etc/ssh/ssh_host_*",
  // Network client state. systemd-networkd stores DUID + lease keyed
  // by interface; without a wipe, the fork's networkd starts up
  // claiming to be the source and DHCP serves stale answers.
  "sudo rm -rf /var/lib/systemd/network/* /var/lib/dhcp/*",
  // The MAC-pinned netplan cloud-init wrote on the source's first
  // boot. The fork has a different MAC (lume regenerates it on
  // create), so this file's match clause won't fire and the
  // interface stays down. Cloud-init re-runs on the new instance-id
  // and writes a fresh netplan with the new MAC.
  "sudo rm -f /etc/netplan/50-cloud-init.yaml /etc/netplan/00-cloud-init-fallback.yaml",
  // Welld's first-boot marker — gone so welld waits for cloud-init
  // on the fork instead of declaring it ready immediately.
  "sudo rm -f /etc/.well-ready",
  // Hostname last so anything above that still wanted to read it
  // (cloud-init clean shouldn't, but be defensive) gets a value.
  "sudo truncate -s 0 /etc/hostname",
].join(" && ");

export interface RinseResult {
  ok: boolean;
  exitCode: number;
  stderr: string;
}

// Pure(-ish) — exposed for the daemon. Caller's responsibility to
// ensureRunning the well first. Returns the exit code + stderr; doesn't
// throw on rinse failure (caller decides what to do).
export async function rinseWell(opts: {
  name: string;
  ip: string;
  user?: string;
}): Promise<RinseResult> {
  const user = opts.user ?? "well";
  const proc = spawn(
    [
      "ssh",
      "-o", "StrictHostKeyChecking=no",
      "-o", "UserKnownHostsFile=/dev/null",
      "-o", "ConnectTimeout=10",
      "-o", "LogLevel=ERROR",
      "-i", PATHS.vmSshKey(opts.name),
      `${user}@${opts.ip}`,
      RINSE_SCRIPT,
    ],
    { stdin: "ignore", stdout: "pipe", stderr: "pipe" },
  );
  const stderr = await new Response(proc.stderr).text();
  const exitCode = await proc.exited;
  return { ok: exitCode === 0, exitCode, stderr };
}
