#!/usr/bin/env bash
# Install welld-dhcp-helper at /usr/local/sbin + sudoers NOPASSWD entry.
#
# One-time setup. Reversible via uninstall-dhcp-helper.sh.
#
# Privilege model (matches A.3 egress design recommendation 1B):
# the helper binary runs as root for the narrow operation of editing
# /var/db/dhcpd_leases. Welld stays as `pete` and shells out via
# `sudo -n /usr/local/sbin/welld-dhcp-helper ...`. The sudoers entry
# grants NOPASSWD to the calling user for ONLY that exact path — no
# wildcard, no other binaries.
#
# Run as your normal user (NOT sudo). This script will prompt for sudo
# password once when needed.

set -euo pipefail

if [ "$(id -u)" = "0" ]; then
  echo "Don't run as root — this installs the helper, which welld then" >&2
  echo "invokes via sudo. Run as your normal user." >&2
  exit 1
fi

HELPER_SRC="$(cd "$(dirname "$0")" && pwd)/welld-dhcp-helper.sh"
HELPER_DST="/usr/local/sbin/welld-dhcp-helper"
SUDOERS_FILE="/etc/sudoers.d/welld-dhcp"
CALLER_USER="$(id -un)"

if [ ! -f "$HELPER_SRC" ]; then
  echo "Helper source missing: $HELPER_SRC" >&2
  exit 1
fi

echo "Installing welld-dhcp-helper:"
echo "  source:  $HELPER_SRC"
echo "  target:  $HELPER_DST"
echo "  sudoers: $SUDOERS_FILE (NOPASSWD for $CALLER_USER)"
echo ""

# 1. Copy helper to /usr/local/sbin, set ownership + mode.
# /usr/local/sbin/ doesn't exist on stock macOS — create with sane perms first.
HELPER_DIR="$(dirname "$HELPER_DST")"
if [ ! -d "$HELPER_DIR" ]; then
  sudo install -d -m 0755 -o root -g wheel "$HELPER_DIR"
  echo "✓ created $HELPER_DIR"
fi
sudo install -m 0755 -o root -g wheel "$HELPER_SRC" "$HELPER_DST"
echo "✓ helper installed at $HELPER_DST"

# 2. Sudoers entry. Use a temp file + visudo -cf to validate before moving
#    into place — a malformed sudoers file would lock you out of sudo.
TMP_SUDOERS=$(mktemp)
trap 'rm -f "$TMP_SUDOERS"' EXIT
cat > "$TMP_SUDOERS" <<EOF
# Wells DHCP helper — grants NOPASSWD for the narrow dhcpd_leases edit
# operation. Generated by scripts/install-dhcp-helper.sh.
$CALLER_USER ALL=(root) NOPASSWD: $HELPER_DST
EOF

sudo visudo -cf "$TMP_SUDOERS" >/dev/null
echo "✓ sudoers entry validated"

sudo install -m 0440 -o root -g wheel "$TMP_SUDOERS" "$SUDOERS_FILE"
echo "✓ sudoers entry installed at $SUDOERS_FILE"

# 3. Smoke test: can we invoke without password?
echo ""
echo "Smoke test: invoking helper with no-op verb..."
if sudo -n "$HELPER_DST" 2>/dev/null; then
  echo "(unexpected: helper accepted no args — should have shown usage)"
else
  # The helper's usage path exits 64; sudo -n succeeded if we got here.
  echo "✓ sudo -n works (helper showed usage as expected)"
fi

echo ""
echo "Install complete. Welld will now auto-release DHCP leases on well destroy."
echo "Manual flush: sudo /usr/local/sbin/welld-dhcp-helper flush-all"
