#!/usr/bin/env bash
# One-command wells bootstrap. Runs from inside the repo checkout and
# brings up the full local substrate: engine + CLI + dhcp helper +
# welld + menu bar — all reboot-survivable.
#
# This is the BASE install. The optional public-URL bridge
# (cloudflared) is separate and not needed for local use — see
# docs/install.md.
#
# Usage:
#   scripts/install.sh [--tag <release-tag>]
#
# The signed engine bundle (bin/vwell.app) and the menu bar app
# (bin/WellsMenuBar.app) are GitHub release assets — they can't be
# rebuilt on an arbitrary machine (Developer ID + provisioning
# profile). install.sh uses a local copy if one is present (dev
# machines that ran scripts/build-vwell.sh), otherwise downloads it
# from the release (default: latest; override with --tag).
#
# Idempotent — safe to re-run.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

TAG=""
while [ $# -gt 0 ]; do
  case "$1" in
    --tag) TAG="${2:-}"; shift 2 ;;
    -h|--help) sed -n '2,19p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "unknown arg: $1 (try --help)" >&2; exit 1 ;;
  esac
done

# Download a release asset into bin/ and unzip it. $1 = asset filename.
download_asset() {
  local asset="$1"
  if ! command -v gh >/dev/null 2>&1; then
    echo "no local bin/${asset%.zip} and gh is not on PATH." >&2
    echo "Either install gh, or build from source with scripts/build-vwell.sh" >&2
    echo "(needs Xcode CLT + the signing identity + provisioning profile)." >&2
    exit 1
  fi
  echo "    downloading $asset from release ${TAG:-<latest>}"
  if [ -n "$TAG" ]; then
    gh release download "$TAG" --pattern "$asset" --dir "$ROOT/bin" --clobber
  else
    gh release download --pattern "$asset" --dir "$ROOT/bin" --clobber
  fi
  ( cd "$ROOT/bin" && unzip -oq "$asset" && rm -f "$asset" )
}

# ── 1. Preflight ──────────────────────────────────────────────────
echo "==> preflight"
ARCH="$(uname -m)"
if [ "$ARCH" != "arm64" ]; then
  echo "wells targets Apple Silicon (arm64); this host is $ARCH" >&2
  exit 1
fi
BUN_PATH="$(command -v bun || true)"
if [ -z "$BUN_PATH" ]; then
  echo "bun not on PATH — install it first:" >&2
  echo "  curl -fsSL https://bun.sh/install | bash" >&2
  exit 1
fi
echo "    arch: $ARCH    bun: $BUN_PATH"

# ── 2. Engine — bin/vwell.app + bin/vwell wrapper ─────────────────
echo "==> engine"
if [ -d "$ROOT/bin/vwell.app" ]; then
  echo "    using local bin/vwell.app"
else
  download_asset "vwell.app.zip"
fi
# (Re)generate the wrapper. Paths derive from $ROOT at install time —
# never a hardcoded stale path (the splites→wells rename burned us on
# exactly this). The inner binary keeps the upstream name "lume" —
# see scripts/build-vwell.sh for the codesign reason.
cat > "$ROOT/bin/vwell" <<WRAP
#!/bin/sh
exec "$ROOT/bin/vwell.app/Contents/MacOS/lume" "\$@"
WRAP
chmod +x "$ROOT/bin/vwell"
echo "    wrapper: bin/vwell → bin/vwell.app/Contents/MacOS/lume"

# ── 3. CLI — the `well` command ───────────────────────────────────
echo "==> cli"
mkdir -p "$HOME/.local/bin"
cat > "$HOME/.local/bin/well" <<CLI
#!/usr/bin/env bash
# Generated by scripts/install.sh — paths derived at install time.
exec "$BUN_PATH" "$ROOT/cli/well.ts" "\$@"
CLI
chmod +x "$HOME/.local/bin/well"
echo "    well → ~/.local/bin/well"
case ":$PATH:" in
  *":$HOME/.local/bin:"*) ;;
  *) echo "    note: ~/.local/bin isn't on your PATH — add it to run 'well' directly" ;;
esac

# ── 4. DHCP helper — privileged, prompts for sudo once ────────────
echo "==> dhcp helper"
bash "$ROOT/scripts/install-dhcp-helper.sh"

# ── 5. welld daemon — launchd agent, auto-starts, survives reboot ─
echo "==> welld"
bash "$ROOT/scripts/install-launchd.sh"

# ── 6. Menu bar app — at-a-glance substrate health ────────────────
echo "==> menu bar"
if [ ! -d "$ROOT/bin/WellsMenuBar.app" ] && command -v gh >/dev/null 2>&1; then
  download_asset "WellsMenuBar.app.zip" || true
fi
# install-menubar.sh builds it via swiftc if still missing. A menu-bar
# failure is non-fatal — the substrate itself is already up.
bash "$ROOT/scripts/install-menubar.sh" || \
  echo "    menu bar install failed (non-fatal — welld + CLI are up)"

# ── 7. Verify ─────────────────────────────────────────────────────
echo "==> verify"
if curl -sS --max-time 5 http://127.0.0.1:7878/healthz >/dev/null 2>&1; then
  echo "    welld /healthz: ok"
else
  echo "    welld not answering /healthz — check ~/.wells/welld.log" >&2
  exit 1
fi
if "$HOME/.local/bin/well" list >/dev/null 2>&1; then
  echo "    well CLI: ok"
else
  echo "    well CLI: 'well list' failed (welld may still be resurrecting wells)"
fi

echo ""
echo "wells is up — welld + menu bar are launchd agents, so they survive reboot."
echo "  CLI:                            well list  |  well create <name>  |  ..."
echo "  API token (for cells/clients):  ~/.wells/token"
echo "  daemon log:                     ~/.wells/welld.log"
echo "  public-URL bridge (optional):   docs/install.md"
